name: Feature Request
description: Suggest a new feature or improvement for Ability Buddy
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
assignees:
  - your-username
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Community input is essential for making Ability Buddy more useful for everyone.
        
  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like to see?
      description: A clear description of what you'd like to be added or changed.
      placeholder: I would like to see...
    validations:
      required: true
      
  - type: textarea
    id: problem-solving
    attributes:
      label: What problem does this solve?
      description: Explain the problem this feature would solve or the need it would address.
      placeholder: This would help users by... / This would solve the problem of...
    validations:
      required: true
      
  - type: textarea
    id: user-story
    attributes:
      label: User story
      description: Describe how a user would interact with this feature.
      placeholder: As a [type of user], I want [goal] so that [benefit/reason]
      
  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Very important
        - Critical need
    validations:
      required: true
      
  - type: dropdown
    id: user-type
    attributes:
      label: What type of user would benefit most?
      multiple: true
      options:
        - Resource browsers (don't create accounts)
        - Resource contributors (create and share resources)
        - Users with mobility disabilities
        - Users with visual disabilities
        - Users with hearing disabilities
        - Users with cognitive disabilities
        - Users with chronic illnesses
        - Caregivers and family members
        - All users
    validations:
      required: true
      
  - type: textarea
    id: accessibility-considerations
    attributes:
      label: Accessibility considerations
      description: How should this feature work with screen readers, keyboard navigation, or other assistive technologies?
      placeholder: This feature should... / Users with disabilities might need...
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Have you considered any alternative ways to solve this problem?
      placeholder: Other ways this could work...
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples that might help explain your idea.
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our community guidelines
      options:
        - label: I agree to be respectful and constructive in my communication
          required: true 